import { useEffect, useRef, useState } from "react";
import * as Cesium from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";
import { X, Layers3, RotateCcw } from "lucide-react";

window.CESIUM_BASE_URL = "/cesium";
const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const localMock = { routes: [{ id: "local", name: "Mock expedition route", coordinates: [[-70, -65], [-20, -72], [40, -68]] }], icebergs: [{ id: "local-berg", name: "Mock iceberg", lon: 20, lat: -70 }], forecast: [{ id: "local-zone", name: "Mock forecast zone", polygon: [[-20, -65], [30, -65], [30, -75], [-20, -75]] }] };

export default function GlobeModal({ onClose }) {
  const host = useRef(null); const viewerRef = useRef(null);
  const [status, setStatus] = useState("loading"); const [updatedAt, setUpdatedAt] = useState("");
  const [visibleLayers, setVisibleLayers] = useState({ routes: true, icebergs: true, forecast: true });
  useEffect(() => {
    document.body.style.overflow = "hidden"; const previousBase = window.CESIUM_BASE_URL; window.CESIUM_BASE_URL = "/cesium"; let cancelled = false;
    const start = async () => { let data = localMock; try { const response = await fetch(`${API}/geo/overview`); const json = await response.json(); if (json?.mocked) { data = json; setUpdatedAt(new Date(json.updated_at).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) + " UTC"); } } catch (error) { console.warn("Using local mock globe data", error); } try {
      const viewer = new Cesium.Viewer(host.current, { baseLayer: false, terrain: false, animation: false, timeline: false, geocoder: false, homeButton: false, sceneModePicker: false, navigationHelpButton: false, requestRenderMode: true }); viewerRef.current = viewer; viewer.scene.globe.baseColor = Cesium.Color.fromCssColorString("#15364a"); viewer.camera.setView({ destination: Cesium.Cartesian3.fromDegrees(20, -78, 14000000) });
      if (cancelled) return; data.routes.forEach((route) => viewer.entities.add({ name: route.name, polyline: { positions: Cesium.Cartesian3.fromDegreesArray(route.coordinates.flat()), width: 4, material: Cesium.Color.fromCssColorString("#38bdf8") } })); data.icebergs.forEach((berg) => viewer.entities.add({ name: berg.name, position: Cesium.Cartesian3.fromDegrees(berg.lon, berg.lat), point: { pixelSize: 11, color: Cesium.Color.WHITE, outlineColor: Cesium.Color.fromCssColorString("#00d4b2"), outlineWidth: 3 }, label: { text: berg.name, font: "12px Outfit", fillColor: Cesium.Color.WHITE, pixelOffset: new Cesium.Cartesian2(0, -18) } })); data.forecast.forEach((zone) => viewer.entities.add({ name: zone.name, polygon: { hierarchy: Cesium.Cartesian3.fromDegreesArray(zone.polygon.flat()), material: Cesium.Color.ORANGE.withAlpha(0.24), outline: true, outlineColor: Cesium.Color.ORANGE } })); setStatus("ready"); viewer.scene.requestRender();
    } catch (error) { console.error(error); setStatus("fallback"); } }; start();
    return () => { cancelled = true; document.body.style.overflow = ""; window.CESIUM_BASE_URL = previousBase; if (viewerRef.current && !viewerRef.current.isDestroyed()) viewerRef.current.destroy(); };
  }, []);
  useEffect(() => { if (!viewerRef.current) return; viewerRef.current.entities.values.forEach((entity) => { if (entity.polyline) entity.show = visibleLayers.routes; if (entity.point) entity.show = visibleLayers.icebergs; if (entity.polygon) entity.show = visibleLayers.forecast; }); viewerRef.current.scene.requestRender(); }, [visibleLayers]);
  const toggleLayer = (layer) => setVisibleLayers((current) => ({ ...current, [layer]: !current[layer] }));
  return <div className="globe-modal" role="dialog" aria-modal="true" aria-label="Antarctic route explorer" data-testid="globe-modal"><div ref={host} className={`globe-canvas ${status === "fallback" ? "globe-hidden" : ""}`} data-testid="cesium-globe-canvas" />{status === "fallback" && <div className="globe-fallback" data-testid="globe-fallback"><div className="fallback-map">ANTARCTICA<br /><span>MOCK ROUTES · MOCK ICEBERGS · MOCK FORECAST</span></div><p>3D rendering is unavailable. The layer set remains available as local mocked data.</p></div>}<div className="globe-topbar"><div><span className="eyebrow">ICE ROUTE / LIVE VIEW</span><h2 data-testid="globe-title">Antarctic route explorer</h2></div><button className="icon-button" onClick={onClose} aria-label="Close globe" data-testid="close-globe-button"><X size={20} /></button></div><div className="globe-panel" data-testid="globe-status-panel"><div className="mock-badge">MOCKED DATA · NOT OPERATIONAL</div><p data-testid="globe-updated-at">Research layer preview · {updatedAt || "Loading timestamp…"}</p><div className="layer-list"><span className="eyebrow">DATA LAYERS</span>{[["routes", "Vessel routes", "cyan"], ["icebergs", "Iceberg locations", "white"], ["forecast", "Forecast risk", "orange"]].map(([key, label, color]) => <button key={key} className="layer-toggle" onClick={() => toggleLayer(key)} data-testid={`toggle-${key}-layer`}><span className={`layer-dot ${color}`} />{label}<span className={`switch ${visibleLayers[key] ? "on" : ""}`} /></button>)}</div></div><button className="reset-view" onClick={() => viewerRef.current?.camera.setView({ destination: Cesium.Cartesian3.fromDegrees(20, -78, 14000000) })} data-testid="reset-globe-view"><RotateCcw size={15} /> Reset view</button><div className="globe-attribution"><Layers3 size={14} /> CesiumJS visualization · MOCKED</div></div>;
}